name: Sync qist/tvbox to tvbox folder
on:
  schedule:
    - cron: '19 3 * * *' # UTC 03:17 = 北京时间 11:15
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你当前web仓库代码
        uses: actions/checkout@v4

      - name: 拉取 qist/tvbox 上游源码
        uses: actions/checkout@v4
        with:
          repository: qist/tvbox
          ref: master
          path: upstream

      - name: 复制全部文件到 tvbox 子目录（不碰原有文件）
        run: |
          mkdir -p ./tvbox
          cp -r upstream/* ./tvbox/
          rm -rf upstream

      - name: 提交更新
        run: |
          git config --global user.name "SyncBot"
          git config --global user.email "sync@example.com"
          git add tvbox/
          git commit -m "auto sync qist/tvbox latest" || echo "无变更无需提交"
          git push